### ISSUE TITLE
Authentik OIDC redirects to invalid or localhost URL

### ISSUE THREAD

**Issue by M-Davies** [factionsecurity/faction#82]
# Overview

I am selfhosting Faction on my cloud server and have an issue where Faction's OIDC redirection logic does not seem to redirect me to the correct callback URL.

# Environement
- OIDC Provider is Authentik
- Faction is running inside a docker container as part of the docker compose stack shown below: 

*Note all read domains have been replaced with `my.tld` and all real credentials replaced with `OMITTED` for privacy*
```yml
version: "3.7"

networks:
  faction-net:
    external: false
  sso:
    external: true

services:
  faction-mongo:
    container_name: faction-mongo
    networks:
      - faction-net
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - '~/.faction/data:/data/db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=OMITTED'
      - 'MONGO_INITDB_ROOT_PASSWORD=OMITTED'
    restart: unless-stopped

  tomcat-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: base_app
    container_name: faction-web
    networks:
      - sso
      - faction-net
    environment:
        - 'FACTION_REPORT_STORAGE=local'
        - 'FACTION_MONGO_HOST=faction-mongo'
        - 'FACTION_MONGO_DATABASE=faction'
        - 'FACTION_MONGO_USER=OMITTED'
        - 'FACTION_MONGO_PASSWORD=OMITTED'
        - 'FACTION_SECRET_KEY=OMITTED'
        - 'FACTION_OAUTH_CALLBACK=https://faction.internal.my.tld/oauth/callback?client_name=OidcClient'
        - 'FACTION_APPSTORE_ENABLED=true'
    links:
      - faction-mongo
    command: ["/usr/local/tomcat/bin/catalina.sh", "run"]
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - faction-mongo
    restart: unless-stopped

postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    container_name: authentik-postgresql
    networks:
      - authentik-internals
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    container_name: authentik-redis
    networks:
      - authentik-internals
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    restart: unless-stopped
    container_name: authentik-server
    networks:
      - sso
      - authentik-internals
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "127.0.0.1:${COMPOSE_PORT_HTTP:-9000}:9000"
      - "127.0.0.1:${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    restart: unless-stopped
    container_name: authentik-worker
    networks:
      - authentik-internals
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

  authentik-ldap-outpost:
    image: ghcr.io/goauthentik/ldap:latest
    container_name: authentik-ldap-outpost
    restart: unless-stopped
    networks:
      - sso
      - authentik-internals
    ports:
      - 127.0.0.1:389:3389
      - 127.0.0.1:636:6636
    environment:
      AUTHENTIK_HOST: https://auth.my.tld
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: OMITTED

volumes:
  database:
    driver: local
  redis:
    driver: local
```
- Faction is configured to use OIDC authentication with the following discovery URI: `https://auth.my.tld/application/o/faction/.well-known/openid-configuration`
- The authentik OIDC provider looks like this (these are not the full settings, I can provide more details if they are needed):

![image](https://github.com/user-attachments/assets/469ba232-4736-4ae4-bd2b-0a888f17adbf)

- The faction interface itself is exposed with nginx to a network range only accessible via a Wireguard VPN range:
```conf
server {
    listen 10.66.66.1:443 ssl http2;

    # Set vars
    set $tld "internal.my.tld";
    set $name "faction";
    server_name faction.internal.my.tld;

    # Headers
    add_header 'Strict-Transport-Security' "max-age=31536000" 'always';
    add_header X-XSS-Protection "0"; # Do NOT enable. This is obsolete/dangerous
    add_header X-Content-Type-Options "nosniff";

    # Block access by direct IP
    if ( $host != $server_name ) {
        return 444; #CONNECTION CLOSED WITHOUT RESPONSE
    }

    # Add robots.txt
    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }
    
    # TLS/SSL Settings
    ssl_certificate /etc/letsencrypt/live/internal.my.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/internal.my.tld/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/internal.my.tld/chain.pem;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Setup logging
    access_log /var/log/nginx/$name-access.log stripsecrets;
    error_log /var/log/nginx/$name-error.log;

    location / {
        # Allow VPN and local clients, deny all others
        allow 10.66.66.0/24;
        allow 127.0.0.0/24;
        deny all;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://127.0.0.1:8081;
    }
}
```

# Error
The problem I have is with the redirect after the user has successfully authenticated to Authentik. If the configuration is identical to the above, the following error is shown after the user has authenticated to Authentik successfully:

![2024-11-07 14_00_08-Window](https://github.com/user-attachments/assets/1c6a90a4-1d82-45d1-9215-50fdf97928a9)

An identical error log appears in Authentik:
```json
{"auth_via": "session", "domain_url": "auth.my.tld", "event": "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).", "host": "auth.my.tld", "level": "warning", "logger": "authentik.providers.oauth2.views.authorize", "pid": 80162, "request_id": "15967659903f4fd58fa74df3946fcabc", "schema_name": "public", "timestamp": "2024-11-07T14:00:06.100560"}
```

This is the final URL: `https://auth.my.tld/application/o/authorize/?max_age=0&scope=openid+profile+email&display=popup&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth%2Fcallback%3Fclient_name%3DOidcClient&state=0aff847c7c&code_challenge_method=S256&prompt=select_account&nonce=OMITTED&client_id=OMITTED&code_challenge=OMITTED`

As you can see, the `redirect_uri` is incorrectly set to a localhost address. If I change the `Redirect URIs/Origins (RegEx)` setting in Authentik to the insecure wildcard, you can see that I am redirected to an invalid localhost address: `http://localhost:8080/oauth/callback?client_name=OidcClient&code=OMITTED`

However, the code that I am provided is valid and I can now login to Faction if I change `http://localhost:8080` in the URL to the correct `https://faction.internal.my.tld`. Authentik's logs also show that authentication was successful:

```json
{"auth_via": "session", "domain_url": "auth.my.tld", "event": "/application/o/authorize/?max_age=0&scope=openid+profile+email&display=popup&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth%2Fcallback%3Fclient_name%3DOidcClient&state=0aff847c7c&code_challenge_method=S256&prompt=select_account&nonce=OMITTED&client_id=OMITTED&code_challenge=OMITTED", "host": "auth.my.tld", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 80162, "remote": "10.66.66.2", "request_id": "15967659903f4fd58fa74df3946fcabc", "runtime": 10, "schema_name": "public", "scheme": "https", "status": 400, "timestamp": "2024-11-07T14:00:06.103486", "user": "OMITTED", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"}
```

My suspicion is that somewhere in either my Authentik or Faction settings, the `FACTION_OAUTH_CALLBACK` variable is not being honoured but I'm not 100% sure why or where. I'd appreciate a 2nd pair of eyes in discovering what I'm doing wrong. I'm also happy to send over more debugging info if it's needed. Thanks!
